// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvq1vME_SGLQBt9kOcqkHpu85fMLNHcoY',
    appId: '1:843549430890:web:5a4a7d70e066da2ad4e613',
    messagingSenderId: '843549430890',
    projectId: 'stapp-ebacb',
    authDomain: 'stapp-ebacb.firebaseapp.com',
    databaseURL: 'https://stapp-ebacb-default-rtdb.firebaseio.com',
    storageBucket: 'stapp-ebacb.firebasestorage.app',
    measurementId: 'G-Z3023YVHEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALW3TbC7RMPZTBIv_KPyyBtZjMnWSRfRE',
    appId: '1:843549430890:android:d8480808eaa88637d4e613',
    messagingSenderId: '843549430890',
    projectId: 'stapp-ebacb',
    databaseURL: 'https://stapp-ebacb-default-rtdb.firebaseio.com',
    storageBucket: 'stapp-ebacb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcXU8p--Ls8ixe_LeYklBuYlxDHDlpOvc',
    appId: '1:843549430890:ios:a379f1810418a2e7d4e613',
    messagingSenderId: '843549430890',
    projectId: 'stapp-ebacb',
    databaseURL: 'https://stapp-ebacb-default-rtdb.firebaseio.com',
    storageBucket: 'stapp-ebacb.firebasestorage.app',
    iosBundleId: 'com.example.testproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcXU8p--Ls8ixe_LeYklBuYlxDHDlpOvc',
    appId: '1:843549430890:ios:a379f1810418a2e7d4e613',
    messagingSenderId: '843549430890',
    projectId: 'stapp-ebacb',
    databaseURL: 'https://stapp-ebacb-default-rtdb.firebaseio.com',
    storageBucket: 'stapp-ebacb.firebasestorage.app',
    iosBundleId: 'com.example.testproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvq1vME_SGLQBt9kOcqkHpu85fMLNHcoY',
    appId: '1:843549430890:web:00a9dc957c7dee05d4e613',
    messagingSenderId: '843549430890',
    projectId: 'stapp-ebacb',
    authDomain: 'stapp-ebacb.firebaseapp.com',
    databaseURL: 'https://stapp-ebacb-default-rtdb.firebaseio.com',
    storageBucket: 'stapp-ebacb.firebasestorage.app',
    measurementId: 'G-P0YNHPCGWL',
  );
}
